version: "3.8"

services:
  webapp:
    build: ./
    ports:
      - "8080:8080"
    networks:
      - go-be
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: my_postgres
    restart: unless-stopped
    env_file: "example.env"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      TZ: UTC
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - go-be

networks:
  go-be:
volumes:
  postgres_data:
