version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your-password
      POSTGRES_DB: calhounio_demo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    build: .
    container_name: go_app
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: your-password
      DB_NAME: calhounio_demo
    depends_on:
      - db
    networks:
      - app-network
    ports:
      - "8080:8080"

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
