definitions:
  models.AuthReponse:
    properties:
      token:
        type: string
    type: object
  models.RegisterDto:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
    type: object
  models.User:
    properties:
      email:
        type: string
      id:
        type: integer
      name:
        type: string
      password:
        type: string
    type: object
  response_error.ResponseError:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
info:
  contact: {}
paths:
  /auth/register:
    post:
      consumes:
      - application/json
      description: Register account
      parameters:
      - description: User registration data
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/models.RegisterDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.AuthReponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response_error.ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response_error.ResponseError'
      summary: Register account
      tags:
      - auth
  /user:
    get:
      description: return list of all users from the database
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
      summary: return list of all
      tags:
      - Users
swagger: "2.0"
